server:
  port: ${PORT:0}

spring:
  application:
    name: catalog-service

  devtools:
    restart:
      enabled: true

  mvc:
    static-path-pattern: '/photos/**'

  web:
    resources:
      #       static-locations: 'classpath:/anything'
      static-locations: 'file:/Users/philipheur/practice/gradle/HShop/photos/catalog'

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
  #    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  #    properties:
  #      hibernate:
  #        dialect: org.hibernate.dialect.PostgreSQL9Dialect
  datasource:
    url: jdbc:postgresql://192.168.50.141:5433/hshop?currentSchema=catalog&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified
    username: postgres
    password: qwe123
    driver-class-name: org.postgresql.Driver
    platform: postgres

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  thymeleaf:
    check-template-location: false

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}


management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: "ALWAYS"
  health:
    circuitbreakers:
      enabled: true


logging:
  level:
    net:
      philipheur:
        hshop:
          catalogservice:
            exchange:
              SettingsServiceClient: DEBUG

resilience4j:
  circuitbreaker:
    instances:
      settings-service:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 1
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        waitDurationInOpenState: 10s


#    init:
#      mode: ALWAYS
#      schema-locations: classpath:init-schema.sql