server:
  port: 8080


spring:
  application:
    name: gateway-service
  devtools:
    restart:
      enabled: true

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: gateway-actuator
          uri: lb://GATEWAY-SERVICE
          predicates:
            - Path=/gateway-service/actuator/**
            - Method=GET,POST
          filters:
            - RewritePath=/gateway-service/?(?<segment>.*), /$\{segment}

        - id: users-get
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/api/users/**,/user-service/api/roles,/user-service/photos/**,/user-service/h2-console/**
            - Method=GET,PUT,POST,DELETE
          filters:
            - RewritePath=/user-service/?(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter

        - id: users-login
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/api/auth/**
            - Method=POST
          filters:
            - RewritePath=/user-service/?(?<segment>.*), /$\{segment}

        - id: users-actuator
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/actuator/**
            - Method=GET,POST
          filters:
            - RewritePath=/user-service/?(?<segment>.*), /$\{segment}

        - id: catalog-actuator
          uri: lb://CATALOG-SERVICE
          predicates:
            - Path=/catalog-service/actuator/**
            - Method=GET,POST
          filters:
            - RewritePath=/catalog-service/?(?<segment>.*), /$\{segment}

        - id: catalog-categories-list
          uri: lb://CATALOG-SERVICE
          predicates:
            - Path=/catalog-service/api/categories/**,/catalog-service/photos/**
            - Method=GET
          filters:
            - RewritePath=/catalog-service/?(?<segment>.*), /$\{segment}

        - id: catalog-brand-list
          uri: lb://CATALOG-SERVICE
          predicates:
            - Path=/catalog-service/api/brands/**
            - Method=GET
          filters:
            - RewritePath=/catalog-service/?(?<segment>.*), /$\{segment}

        - id: catalog-products-list
          uri: lb://CATALOG-SERVICE
          predicates:
            - Path=/catalog-service/api/products/**
            - Method=GET
          filters:
            - RewritePath=/catalog-service/?(?<segment>.*), /$\{segment}

        - id: catalog-products-create
          uri: lb://CATALOG-SERVICE
          predicates:
            - Path=/catalog-service/api/products
            - Method=POST
          filters:
            - RewritePath=/catalog-service/?(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter

        - id: settings-actuator
          uri: lb://SETTINGS-SERVICE
          predicates:
            - Path=/settings-service/actuator/**
            - Method=GET,POST
          filters:
            - RewritePath=/settings-service/?(?<segment>.*), /$\{segment}

        - id: settings-list
          uri: lb://SETTINGS-SERVICE
          predicates:
            - Path=/settings-service/api/settings/**,/settings-service/api/currencies/**,/settings-service/photos/**
            - Method=GET,PUT,POST,DELETE
          filters:
            - RewritePath=/settings-service/?(?<segment>.*), /$\{segment}

        - id: customer-actuator
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/customer-service/actuator/**
            - Method=GET,POST
          filters:
            - RewritePath=/customer-service/?(?<segment>.*), /$\{segment}

        - id: customer-apis
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/customer-service/api/customers/**
            - Method=GET,PUT,POST,DELETE
          filters:
            - RewritePath=/customer-service/?(?<segment>.*), /$\{segment}

        - id: customer-login
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/customer-service/login/**
            - Method=PUT
          filters:
            - RewritePath=/customer-service/(?<segment>.*), /$\{segment}

#    default-filters:
#      - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka

logging:
  level:
    org.springframework.cloud.client.loadbalancer: DEBUG


management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway,health,mappings,busrefresh,busenv
