server:
  port: ${PORT:0}

logging:
  level:
    ROOT: info

spring:
  application:
    name: user-service

  mvc:
    static-path-pattern: '/photos/**'

  devtools:
    restart:
      enabled: true

  web:
    resources:
      #       static-locations: 'classpath:/anything'
      static-locations: 'file:/Users/philipheur/practice/gradle/HShop/photos/users'

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

  #  h2:
  #    console:
  #      enabled: true
  #      path: /h2-console
  #      settings:
  #        web-allow-others: true
  #        trace: false

  #  datasource:
  #    url: jdbc:h2:mem:testdb
  #    username: sa
  #    password: password
  #    driverClassName: org.h2.Driver
  #  sql:
  #    init:
  #      mode: ALWAYS
  #      schema-locations: classpath:init-schema.sql,classpath:init-data.sql

  datasource:
    url: jdbc:postgresql://192.168.50.141:5433/hshop?currentSchema=users&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified
    username: postgres
    password: qwe123
    driver-class-name: org.postgresql.Driver
    platform: postgres


  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  thymeleaf:
    check-template-location: false

gateway:
  ip: '192.168.50.167'

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}


management:
  endpoints:
    web:
      exposure:
        include: beans,health,mappings,httpexchanges,busrefresh