server:
  port: 8080
  servlet:
    context-path: '/hshopadmin'

spring:
  datasource:
    url: jdbc:mysql://192.168.50.140:3306/hshop
    username: root
    password: qwe123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false