object Dependencies {
    const val SPRING_BOOT_STARTER = "org.springframework.boot:spring-boot-starter:${Versions.SPRING_BOOT}"
    const val SPRING_BOOT_STARTER_LOGGING = "org.springframework.boot:spring-boot-starter-logging:${Versions.SPRING_BOOT}"
    const val SPRING_BOOT_STARTER_TEST = "org.springframework.boot:spring-boot-starter-test:${Versions.SPRING_BOOT}"
    const val SPRING_BOOT_STARTER_JSON = "org.springframework.boot:spring-boot-starter-json:${Versions.SPRING_BOOT}"
    const val SPRING_BOOT_STARTER_DATA_JPA = "org.springframework.boot:spring-boot-starter-data-jpa:${Versions.SPRING_BOOT}"
    const val SPRING_BOOT_STARTER_WEB = "org.springframework.boot:spring-boot-starter-web:${Versions.SPRING_BOOT}"
    const val SPRING_BOOT_STARTER_WEBFLUX = "org.springframework.boot:spring-boot-starter-webflux:${Versions.SPRING_BOOT}"
    const val SPRING_BOOT_STARTER_THYMELEAF = "org.springframework.boot:spring-boot-starter-thymeleaf:${Versions.SPRING_BOOT}"
    const val SPRING_BOOT_STARTER_SECURITY = "org.springframework.boot:spring-boot-starter-security:${Versions.SPRING_BOOT}"
    const val SPRING_BOOT_STARTER_ACTUATOR = "org.springframework.boot:spring-boot-starter-actuator:${Versions.SPRING_BOOT}"
    const val SPRING_BOOT_STARTER_VALIDATION = "org.springframework.boot:spring-boot-starter-validation:${Versions.SPRING_BOOT}"
    const val SPRING_BOOT_STARTER_AOP = "org.springframework.boot:spring-boot-starter-aop:${Versions.SPRING_BOOT}"
    const val SPRING_BOOT_DEVTOOLS = "org.springframework.boot:spring-boot-devtools:${Versions.SPRING_BOOT}"
    const val SPRING_AUTOCONFIGURE = "org.springframework.boot:spring-boot-autoconfigure:${Versions.SPRING_BOOT}"

    const val SPRING_SECURITY_CRYPTO = "org.springframework.security:spring-security-crypto:${Versions.SPRING_SECURITY}"
    const val SPRING_SECURITY_CORE = "org.springframework.security:spring-security-core:${Versions.SPRING_SECURITY}"
    const val SPRING_TX = "org.springframework:spring-tx:${Versions.SPRING}"
    const val SPRING_WEB = "org.springframework:spring-web:${Versions.SPRING}"
    const val SPRING_KAFKA = "org.springframework.kafka:spring-kafka:${Versions.SPRING_KAFKA}"
    const val SPRING_CLOUD_CONFIG_SERVER = "org.springframework.cloud:spring-cloud-config-server"
    const val SPRING_CLOUD_STARTER_CONFIG = "org.springframework.cloud:spring-cloud-starter-config"
    const val SPRING_CLOUD_STARTER_GATEWAY = "org.springframework.cloud:spring-cloud-starter-gateway"
    const val SPRING_CLOUD_STARTER_OPENFEIGN = "org.springframework.cloud:spring-cloud-starter-openfeign"
    const val SPRING_CLOUD_STARTER_BUS_AMQP = "org.springframework.cloud:spring-cloud-starter-bus-amqp"
    const val SPRING_CLOUD_STARTER_NETFLIX_EUREKA_SERVER = "org.springframework.cloud:spring-cloud-starter-netflix-eureka-server"
    const val SPRING_CLOUD_STARTER_NETFLIX_EUREKA_CLIENT = "org.springframework.cloud:spring-cloud-starter-netflix-eureka-client"

    const val JJWT_API="io.jsonwebtoken:jjwt-api:${Versions.JJWT}"
    const val JJWT_IMPL="io.jsonwebtoken:jjwt-impl:${Versions.JJWT}"
    const val JJWT_JACKSON="io.jsonwebtoken:jjwt-jackson:${Versions.JJWT}"

    const val KOTLIN_REFLECT = "org.jetbrains.kotlin:kotlin-reflect:${Versions.KOTLIN}"
    const val JACKSON_MODULE_KOTLIN = "com.fasterxml.jackson.module:jackson-module-kotlin:${Versions.JACKSON_KOTLIN}"
    const val LOMBOK = "org.projectlombok:lombok:${Versions.LOMBOK}"
    const val JUNIT_JUPITER = "org.junit.jupiter:junit-jupiter:${Versions.JUNIT_JUPITER}"
    const val JUNIT_PLATFORM_LAUNCHER = "org.junit.platform:junit-platform-launcher"
    const val MOKITO_KOTLIN = "org.mockito.kotlin:mockito-kotlin:${Versions.MOKITO_KOTLIN}"
    const val COMMON_TEXT = "org.apache.commons:commons-text:${Versions.COMMON_TEXT}"
    const val COMMON_IO = "commons-io:commons-io:${Versions.COMMON_IO}"
    const val KOTLIN_TEST = "org.jetbrains.kotlin:kotlin-test"
    const val POSTGRESQL = "org.postgresql:postgresql:${Versions.POSTGRESQL}"
    const val KAFKA_AVRO_SERIALIZER = "io.confluent:kafka-avro-serializer:${Versions.KAFKA_AVRO_SERIALIZER}"
    const val KOTLIN_GRADLE_PLUGIN = "org.jetbrains.kotlin:kotlin-gradle-plugin:${Versions.KOTLIN}"

    const val RESILIENCE4J = "io.github.resilience4j:resilience4j-spring-boot3:${Versions.RESILIENCE4J}"

    const val WEBJARS_BOOTSTRAP = "org.webjars:bootstrap:${Versions.WEBJARS_BOOTSTRAP}"
    const val WEBJARS_JQUERY = "org.webjars:jquery:${Versions.WEBJARS_JQUERY}"
    const val WEBJARS_LOCATOR_CORE = "org.webjars:webjars-locator-core:0.55"

    const val H2_DATABASE = "com.h2database:h2:${Versions.H2_DATABASE}"
    const val MYSQL_CONNECTOR = "mysql:mysql-connector-java:${Versions.MYSQL_CONNECTOR}"

    const val OPEN_CSV = "com.opencsv:opencsv:${Versions.OPEN_CSV}"
}
